spring:
  profiles:
    active: local
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        min-idle: 100

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydatacollect-server-process
  shutdownGrace: 30

server:
  port: 18082

connect-server:
  host: localhost
  port: 18081

kafka:
  bootstrap-servers: localhost:9092

# user, cipher, finance는 현 상황에서는 연동하지 않는 서비스라 7777처럼 임의 포트로 지정.
# 위 서비스 uri을 지정하지 않으면 grpcConfig에서 channel을 만들 때 에러 발생.
uri:
  collectmydataconnect: localhost:18181
  user: localhost:7777
  cipher: localhost:8888
  finance: localhost:9998

