spring:
  profiles:
    active: local
  application:
    name: collectmydata-capital
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/capital
    name: sa
    password:

banksalad:
  cipher.uri: localhost:9999
  collectmydata-connect.uri: localhost:9998

kafka:
  bootstrap-servers: localhost:9092

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.transaction.interceptor: trace
