spring:
  profiles:
    active: local
  application:
    name: collectmydata-capital
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/capital
    name: sa
    password:

banksalad:
  cipher.uri: localhost:9999
  collectmydata-connect.uri: localhost:9998
