spring:
  profiles:
    active: production
  application:
    name: collectmydatacapital

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydatacapital-server-process
  shutdownGrace: 30

server:
  port: 18082
