spring:
  profiles:
    active: local
  application:
    name: collectmydata-capital
  main:
    web-application-type: none

banksalad:
  cipher.uri: dns:///cipher-headless:18081
  collectmydata-connect.uri: dns:///connect:8080
