spring:
  profiles:
    active: local
  application:
    name: collectmydataconnect

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

management:
  metrics:
    export:
      statsd:
        enabled: true
        flavor: telegraf
        polling-frequency: 5s
        max-packet-length: 5000
        host: localhost
        port: 8126
        publish-unchanged-meters: true
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

banksalad:
  cipher.uri: dns:///cipher-headless:18081
  collectSchedule.uri: dns:///fixme:8080
  auth.uri: dns:///auth-headless:18081
