spring:
  profiles:
    active: local
  application:
    name: collectmydata-connect

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
