spring:
  profiles:
    active: production

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydataconnect-server-process
  shutdownGrace: 30

server:
  port: 18082

organization:
  finance-portal-domain: http://fixme.com

banksalad:
  oauth-callback-url: http://fixme.com
