spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/connect
    name: sa
    password:

organization:
  finance-portal-domain: http://fixme.com

banksalad:
  oauth-callback-url: http://fixme.com

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
