spring:
  profiles:
    active: staging
  application:
    name: collectmydata-oauth
  redis:
    cluster:
      nodes:
        - collect-001.a8qgjr.0001.apn2.cache.amazonaws.com:6379
        - collect-002.a8qgjr.0001.apn2.cache.amazonaws.com:6379
        - collect-003.a8qgjr.0001.apn2.cache.amazonaws.com:6379
organization:
  mydata-client-id: fixme
