spring:
  profiles:
    active: local
  application:
    name: collectmydataoauth
  redis:
    maxActive: 8
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 2
        max-wait: 50000ms

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml

management:
  metrics:
    export:
      statsd:
        enabled: true
        flavor: telegraf
        polling-frequency: 5s
        max-packet-length: 5000
        host: localhost
        port: 8126
        publish-unchanged-meters: true
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

organization:
  mydata-client-id: tmp

connect-server:
  host: connect
  port: 8080

auth-server:
  url: dns:///auth-headless:18081
