spring:
  profiles:
    active: local
  application:
    name: collectmydata-oauth
  redis:
    cluster:
      nodes:
        - localhost:6379
    port: 6379

organization:
  mydata-client-id: tmp

connect-server:
  host: localhost
  port: 9999

auth-server:
  url: localhost:18081
  host: localhost
  port: 9998
