spring:
  profiles:
    active: local
  application:
    name: mydata-oauth
  redis:
    maxActive: 8
    lettuce:
      pool:
        max-active: 50
        max-idle: 10
        min-idle: 2
        max-wait: 50000ms

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    root: debug


organization:
  mydata-client-id: tmp

