spring:
  profiles:
    active: staging
  application:
    name: collectmydata-oauth
  redis:
    cluster:
      nodes:
        - collect.a8qgjr.ng.0001.apn2.cache.amazonaws.com:6379
        - collect-ro.a8qgjr.ng.0001.apn2.cache.amazonaws.com:6379

organization:
  mydata-client-id: fixme
