spring:
  profiles:
    active: production
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://collectmydata-efin:3306
    driver-class-name: org.mariadb.jdbc.Driver
    username: developer
    password: ${PRODUCTION_COLLECTMYDATA_EFIN_DB_PASSWORD}
    hikari:
      maximum-pool-size: 70
      connection-timeout: 5000
      validation-timeout: 4000
      max-lifetime: 60000
    type: com.zaxxer.hikari.HikariDataSource

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydataefin-server-process
  shutdownGrace: 30

server:
  port: 18082
