spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem://localhost/~/ginsu
    name: sa
    password:

grpc:
  port: 18881
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydataginsu-server-process
  shutdownGrace: 30

server:
  port: 18882

logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

kafka:
  bootstrap-servers: localhost:9092
