spring:
  application:
    name: collectmydatafinance

uri:
  collectmydataconnect: dns:///collectmydataconnect-headless:18081
  cipher: fixme
  user: dns:///user-headless:18081
  finance: dns:///finance-headless:18081

