spring:
  profiles:
    active: local

# cipher는 현 상황에서는 연동하지 않는 서비스라 88888처럼 임의 포트로 지정.
# 아래 서비스 uri을 지정하지 않으면 grpcConfig에서 channel을 만들 때 에러 발생.
uri:
  collectmydataconnect: localhost:18181
  cipher: localhost:88888
