package com.banksalad.collectmydata.common.enums;

public enum FinanceSyncItem {
  COLLECTMYDATA_FINANCE_SYNC_ITEM_UNKNOWN,

  /* BANK */
  COLLECTMYDATA_BANK_SYNC_ITEM_ACCOUNT_SUMMARY,
  COLLECTMYDATA_BANK_SYNC_ITEM_DEPOSIT_ACCOUNT_BASIC,
  COLLECTMYDATA_BANK_SYNC_ITEM_DEPOSIT_ACCOUNT_DETAIL,
  COLLECTMYDATA_BANK_SYNC_ITEM_DEPOSIT_ACCOUNT_TRANSACTION,

  COLLECTMYDATA_BANK_SYNC_ITEM_INVEST_ACCOUNT_BASIC,
  COLLECTMYDATA_BANK_SYNC_ITEM_INVEST_ACCOUNT_DETAIL,
  COLLECTMYDATA_BANK_SYNC_ITEM_INVEST_ACCOUNT_TRANSACTION,

  COLLECTMYDATA_BANK_SYNC_ITEM_LOAN_ACCOUNT_BASIC,
  COLLECTMYDATA_BANK_SYNC_ITEM_LOAN_ACCOUNT_DETAIL,
  COLLECTMYDATA_BANK_SYNC_ITEM_LOAN_ACCOUNT_TRANSACTION,

  COLLECTMYDATA_BANK_SYNC_ITEM_COMPLETED,

  /* INVEST */
  COLLECTMYDATA_INVEST_SYNC_ITEM_ACCOUNT_SUMMARY,
  COLLECTMYDATA_INVEST_SYNC_ITEM_ACCOUNT_BASIC,
  COLLECTMYDATA_INVEST_SYNC_ITEM_ACCOUNT_TRANSACTION,
  COLLECTMYDATA_INVEST_SYNC_ITEM_ACCOUNT_PRODUCT,

  COLLECTMYDATA_INVEST_SYNC_ITEM_COMPLETED,

  /* CARD */
  COLLECTMYDATA_CARD_SYNC_ITEM_ACCOUNT_SUMMARY,

  COLLECTMYDATA_CARD_SYNC_ITEM_COMPLETED

}
