package com.banksalad.collectmydata.common.enums;

public enum FinanceSyncItem {
  COLLECTMYDATA_FINANCE_SYNC_ITEM_UNKNOWN,

  /* BANK */
  COLLECTMYDATABANK_SYNC_ITEM_ACCOUNT_SUMMARY,
  COLLECTMYDATABANK_SYNC_ITEM_DEPOSIT_ACCOUNT_BASIC,
  COLLECTMYDATABANK_SYNC_ITEM_DEPOSIT_ACCOUNT_DETAIL,
  COLLECTMYDATABANK_SYNC_ITEM_DEPOSIT_ACCOUNT_TRANSACTION,

  COLLECTMYDATABANK_SYNC_ITEM_INVEST_ACCOUNT_BASIC,
  COLLECTMYDATABANK_SYNC_ITEM_INVEST_ACCOUNT_DETAIL,
  COLLECTMYDATABANK_SYNC_ITEM_INVEST_ACCOUNT_TRANSACTION,

  COLLECTMYDATABANK_SYNC_ITEM_LOAN_ACCOUNT_BASIC,
  COLLECTMYDATABANK_SYNC_ITEM_LOAN_ACCOUNT_DETAIL,
  COLLECTMYDATABANK_SYNC_ITEM_LOAN_ACCOUNT_TRANSACTION,

  COLLECTMYDATABANK_SYNC_ITEM_COMPLETED,

  /* INVEST */
  COLLECTMYDATAINVEST_SYNC_ITEM_ACCOUNT_SUMMARY,
  COLLECTMYDATAINVEST_SYNC_ITEM_ACCOUNT_BASIC,
  COLLECTMYDATAINVEST_SYNC_ITEM_ACCOUNT_TRANSACTION,
  COLLECTMYDATAINVEST_SYNC_ITEM_ACCOUNT_PRODUCT,

  COLLECTMYDATAINVEST_SYNC_ITEM_COMPLETED,

  /* CARD */
  COLLECTMYDATACARD_SYNC_ITEM_CARD_SUMMARY,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_BASIC,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_POINT,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_BILL_BASIC,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_BILL_DETAIL,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_PAYMENT,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_APPROVAL_DOMESTIC_TRANSACTION,
  COLLECTMYDATACARD_SYNC_ITEM_CARD_APPROVAL_OVERSEAS_TRANSACTION,
  COLLECTMYDATACARD_SYNC_ITEM_LOAN_SUMMARY,
  COLLECTMYDATACARD_SYNC_ITEM_LOAN_REVOLVING,
  COLLECTMYDATACARD_SYNC_ITEM_LOAN_SHORT_TERM,
  COLLECTMYDATACARD_SYNC_ITEM_LOAN_LONG_TERM,

  COLLECTMYDATACARD_SYNC_ITEM_COMPLETED,
}
