spring:
  profiles:
    active: production

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydatatelecoms-server-process
  shutdownGrace: 30

server:
  port: 18082
