spring:
  profiles:
    active: staging
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://collectmydatatelecom-cluster.cluster-ciy3wcu0axct.ap-northeast-2.rds.amazonaws.com:3306/telecom?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    driver-class-name: org.mariadb.jdbc.Driver
    username: collectmydatatelecom_was
    password: ${STG_COLLECTMYDATA_TELECOM_DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      connection-timeout: 5000
      validation-timeout: 4000
      max-lifetime: 60000
      minimum-idle: 10
      idle-timeout: 54000
    type: com.zaxxer.hikari.HikariDataSource

grpc:
  port: 18081
  enable-reflection: true
  enabled: true
  in-process-server-name: collectmydatatelecom-server-process
  shutdownGrace: 30

server:
  port: 18082

logging:
  level:
    com.zaxxer.hikari.HikariConfig: INFO
    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO

# kafka broker 설정
kafka:
  bootstrap-servers: b-2.collectmydata.of5yls.c3.kafka.ap-northeast-2.amazonaws.com:9092,b-3.collectmydata.of5yls.c3.kafka.ap-northeast-2.amazonaws.com:9092,b-1.collectmydata.of5yls.c3.kafka.ap-northeast-2.amazonaws.com:9092
