name: CI insu

env:
  module: 'insu'

on:
  - push

jobs:
  tests:
    name: Lint and Test
    runs-on: [self-hosted, jvm]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Test
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_DAAS_PACKAGES_TOKEN: ${{ secrets.GH_DAAS_PACKAGES_TOKEN }}
        run: ./gradlew -s ${{env.module}}:test

#      - name: Send to codecov
#        uses: codecov/codecov-action@v1
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}

  build:
    name: Build
    runs-on: [self-hosted, jvm]
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GH_DAAS_PACKAGES_TOKEN: ${{ secrets.GH_DAAS_PACKAGES_TOKEN }}
        run: ./gradlew clean ${{env.module}}:build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ${{env.module}}
          push: true
          tags: rainist/collectmydata-${{env.module}}:${{ github.sha }}
